//
// AccountAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class AccountAPI: APIBase {
    /**
     Retrieve Companies by account
     
     - parameter accountId: (path) Account ID 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func accountsAccountIdCompaniesGet(accountId accountId: NSUUID, completion: ((data: [AccountCompany]?, error: ErrorType?) -> Void)) {
        accountsAccountIdCompaniesGetWithRequestBuilder(accountId: accountId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Retrieve Companies by account
     - GET /accounts/{accountId}/companies
     - Retrieve list companies of one account
     - responseHeaders: [X-Pagination-Current-Page(Double), X-Pagination-Limit(Double), X-Pagination-Total-Pages(Double), X-Pagination-Total-Count(Double)]
     - responseHeaders: [X-Pagination-Current-Page(Double), X-Pagination-Limit(Double), X-Pagination-Total-Pages(Double), X-Pagination-Total-Count(Double)]
     - responseHeaders: [X-Pagination-Current-Page(Double), X-Pagination-Limit(Double), X-Pagination-Total-Pages(Double), X-Pagination-Total-Count(Double)]
     - responseHeaders: [X-Pagination-Current-Page(Double), X-Pagination-Limit(Double), X-Pagination-Total-Pages(Double), X-Pagination-Total-Count(Double)]
     - examples: [{contentType=application/json, example=[ {
  "companyCode" : "aeiou",
  "companyId" : "046b6c7f-0b8a-43b9-b35d-6489e6daee91",
  "companyName" : "aeiou"
} ]}]
     
     - parameter accountId: (path) Account ID 

     - returns: RequestBuilder<[AccountCompany]> 
     */
    public class func accountsAccountIdCompaniesGetWithRequestBuilder(accountId accountId: NSUUID) -> RequestBuilder<[AccountCompany]> {
        var path = "/accounts/{accountId}/companies"
        path = path.stringByReplacingOccurrencesOfString("{accountId}", withString: "\(accountId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[AccountCompany]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Create company and your data configuration
     
     - parameter accountId: (path) Account ID 
     - parameter body: (body) Company Code 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func createAccountCompany(accountId accountId: NSUUID, body: Body, completion: ((data: InlineResponse201?, error: ErrorType?) -> Void)) {
        createAccountCompanyWithRequestBuilder(accountId: accountId, body: body).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Create company and your data configuration
     - POST /accounts/{accountId}/companies
     - This method operation create a company for a account 
     - examples: [{contentType=application/json, example={
  "id" : 123
}}]
     
     - parameter accountId: (path) Account ID 
     - parameter body: (body) Company Code 

     - returns: RequestBuilder<InlineResponse201> 
     */
    public class func createAccountCompanyWithRequestBuilder(accountId accountId: NSUUID, body: Body) -> RequestBuilder<InlineResponse201> {
        var path = "/accounts/{accountId}/companies"
        path = path.stringByReplacingOccurrencesOfString("{accountId}", withString: "\(accountId)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = body.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<InlineResponse201>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
