//
// TaxConfIBPTAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class TaxConfIBPTAPI: APIBase {
    /**
     create a new Process Type configuration
     
     - parameter taxconfprocess: (body) The pet JSON you want to post 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func createIbptConf(taxconfprocess taxconfprocess: IbptConf, completion: ((data: InlineResponse201?, error: ErrorType?) -> Void)) {
        createIbptConfWithRequestBuilder(taxconfprocess: taxconfprocess).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     create a new Process Type configuration
     - POST /taxconf/ibpt
     - examples: [{contentType=application/json, example={
  "id" : 123
}}]
     
     - parameter taxconfprocess: (body) The pet JSON you want to post 

     - returns: RequestBuilder<InlineResponse201> 
     */
    public class func createIbptConfWithRequestBuilder(taxconfprocess taxconfprocess: IbptConf) -> RequestBuilder<InlineResponse201> {
        let path = "/taxconf/ibpt"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = taxconfprocess.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<InlineResponse201>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     disable a IBPT.
     
     - parameter code: (path) IBPT Code 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func deleteIbptConf(code code: String, completion: ((error: ErrorType?) -> Void)) {
        deleteIbptConfWithRequestBuilder(code: code).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     disable a IBPT.
     - DELETE /taxconf/ibpt/{code}
     
     - parameter code: (path) IBPT Code 

     - returns: RequestBuilder<Void> 
     */
    public class func deleteIbptConfWithRequestBuilder(code code: String) -> RequestBuilder<Void> {
        var path = "/taxconf/ibpt/{code}"
        path = path.stringByReplacingOccurrencesOfString("{code}", withString: "\(code)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     get IBPT information.
     
     - parameter code: (path) IBPT Code 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getIbptConf(code code: String, completion: ((data: IbptConf?, error: ErrorType?) -> Void)) {
        getIbptConfWithRequestBuilder(code: code).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     get IBPT information.
     - GET /taxconf/ibpt/{code}
     - This operation return Process Type configuration 
     - examples: [{contentType=application/json, example={
  "code" : "aeiou",
  "description" : "aeiou",
  "list" : [ {
    "cityTax" : 1.3579000000000001069366817318950779736042022705078125,
    "federalTax" : 1.3579000000000001069366817318950779736042022705078125,
    "importTax" : 1.3579000000000001069366817318950779736042022705078125,
    "state" : { },
    "stateTax" : 1.3579000000000001069366817318950779736042022705078125,
    "source" : "aeiou"
  } ]
}}]
     
     - parameter code: (path) IBPT Code 

     - returns: RequestBuilder<IbptConf> 
     */
    public class func getIbptConfWithRequestBuilder(code code: String) -> RequestBuilder<IbptConf> {
        var path = "/taxconf/ibpt/{code}"
        path = path.stringByReplacingOccurrencesOfString("{code}", withString: "\(code)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<IbptConf>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     retrive list of IBPT.
     
     - parameter accountId: (query) filter the configuration by accountID, if not informed, only the standard configuration will be returned  (optional)
     - parameter date: (query) When informed return valid version configuration for this date  (optional)
     - parameter inactive: (query) return the inactive versions too  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getIbptConfList(accountId accountId: String? = nil, date: NSDate? = nil, inactive: Bool? = nil, completion: ((data: [IbptConf]?, error: ErrorType?) -> Void)) {
        getIbptConfListWithRequestBuilder(accountId: accountId, date: date, inactive: inactive).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     retrive list of IBPT.
     - GET /taxconf/ibpt
     - This operation return Process Type configurations that match with parameters queries 
     - responseHeaders: [X-Pagination-Current-Page(Double), X-Pagination-Limit(Double), X-Pagination-Total-Pages(Double), X-Pagination-Total-Count(Double)]
     - responseHeaders: [X-Pagination-Current-Page(Double), X-Pagination-Limit(Double), X-Pagination-Total-Pages(Double), X-Pagination-Total-Count(Double)]
     - responseHeaders: [X-Pagination-Current-Page(Double), X-Pagination-Limit(Double), X-Pagination-Total-Pages(Double), X-Pagination-Total-Count(Double)]
     - responseHeaders: [X-Pagination-Current-Page(Double), X-Pagination-Limit(Double), X-Pagination-Total-Pages(Double), X-Pagination-Total-Count(Double)]
     - examples: [{contentType=application/json, example=[ {
  "code" : "aeiou",
  "description" : "aeiou",
  "list" : [ {
    "cityTax" : 1.3579000000000001069366817318950779736042022705078125,
    "federalTax" : 1.3579000000000001069366817318950779736042022705078125,
    "importTax" : 1.3579000000000001069366817318950779736042022705078125,
    "state" : { },
    "stateTax" : 1.3579000000000001069366817318950779736042022705078125,
    "source" : "aeiou"
  } ]
} ]}]
     
     - parameter accountId: (query) filter the configuration by accountID, if not informed, only the standard configuration will be returned  (optional)
     - parameter date: (query) When informed return valid version configuration for this date  (optional)
     - parameter inactive: (query) return the inactive versions too  (optional)

     - returns: RequestBuilder<[IbptConf]> 
     */
    public class func getIbptConfListWithRequestBuilder(accountId accountId: String? = nil, date: NSDate? = nil, inactive: Bool? = nil) -> RequestBuilder<[IbptConf]> {
        let path = "/taxconf/ibpt"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "accountId": accountId,
            "date": date?.encodeToJSON(),
            "inactive": inactive
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[IbptConf]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     update a Process Type configuration
     
     - parameter code: (path) IBPT Code 
     - parameter taxconfprocess: (body) The pet JSON you want to post 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func updateIbptConf(code code: String, taxconfprocess: IbptConf, completion: ((error: ErrorType?) -> Void)) {
        updateIbptConfWithRequestBuilder(code: code, taxconfprocess: taxconfprocess).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     update a Process Type configuration
     - PUT /taxconf/ibpt/{code}
     
     - parameter code: (path) IBPT Code 
     - parameter taxconfprocess: (body) The pet JSON you want to post 

     - returns: RequestBuilder<Void> 
     */
    public class func updateIbptConfWithRequestBuilder(code code: String, taxconfprocess: IbptConf) -> RequestBuilder<Void> {
        var path = "/taxconf/ibpt/{code}"
        path = path.stringByReplacingOccurrencesOfString("{code}", withString: "\(code)", options: .LiteralSearch, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = taxconfprocess.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
