/*
 * BR16 - API
 * This documentation is about service accessories that will compose the product BR16, this services are essencial to maintenance and configuration of accounts
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ItemCpom
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-16T18:26:15.214Z")
public class ItemCpom {
  @SerializedName("companyId")
  private String companyId = null;

  @SerializedName("cityCode")
  private String cityCode = null;

  @SerializedName("itemCode")
  private String itemCode = null;

  @SerializedName("code")
  private String code = null;

  public ItemCpom companyId(String companyId) {
    this.companyId = companyId;
    return this;
  }

   /**
   * Company ID
   * @return companyId
  **/
  @ApiModelProperty(example = "null", required = true, value = "Company ID")
  public String getCompanyId() {
    return companyId;
  }

  public void setCompanyId(String companyId) {
    this.companyId = companyId;
  }

  public ItemCpom cityCode(String cityCode) {
    this.cityCode = cityCode;
    return this;
  }

   /**
   * IBGE city code
   * @return cityCode
  **/
  @ApiModelProperty(example = "null", required = true, value = "IBGE city code")
  public String getCityCode() {
    return cityCode;
  }

  public void setCityCode(String cityCode) {
    this.cityCode = cityCode;
  }

  public ItemCpom itemCode(String itemCode) {
    this.itemCode = itemCode;
    return this;
  }

   /**
   * ERP Code
   * @return itemCode
  **/
  @ApiModelProperty(example = "null", required = true, value = "ERP Code")
  public String getItemCode() {
    return itemCode;
  }

  public void setItemCode(String itemCode) {
    this.itemCode = itemCode;
  }

  public ItemCpom code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Code in City
   * @return code
  **/
  @ApiModelProperty(example = "null", required = true, value = "Code in City")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ItemCpom itemCpom = (ItemCpom) o;
    return Objects.equals(this.companyId, itemCpom.companyId) &&
        Objects.equals(this.cityCode, itemCpom.cityCode) &&
        Objects.equals(this.itemCode, itemCpom.itemCode) &&
        Objects.equals(this.code, itemCpom.code);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyId, cityCode, itemCode, code);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ItemCpom {\n");
    
    sb.append("    companyId: ").append(toIndentedString(companyId)).append("\n");
    sb.append("    cityCode: ").append(toIndentedString(cityCode)).append("\n");
    sb.append("    itemCode: ").append(toIndentedString(itemCode)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

