/*
 * BR16 - API
 * This documentation is about service accessories that will compose the product BR16, this services are essencial to maintenance and configuration of accounts
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * LineForGoodsAdi
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-02-16T18:26:15.214Z")
public class LineForGoodsAdi {
  @SerializedName("addNumber")
  private Integer addNumber = null;

  @SerializedName("sequentialNumber")
  private Integer sequentialNumber = null;

  @SerializedName("manufacturerCode")
  private String manufacturerCode = null;

  @SerializedName("adiDiscount")
  private Double adiDiscount = null;

  @SerializedName("drawbackNumber")
  private String drawbackNumber = null;

  public LineForGoodsAdi addNumber(Integer addNumber) {
    this.addNumber = addNumber;
    return this;
  }

   /**
   * aditional sequence number (1 to 100)
   * @return addNumber
  **/
  @ApiModelProperty(example = "null", required = true, value = "aditional sequence number (1 to 100)")
  public Integer getAddNumber() {
    return addNumber;
  }

  public void setAddNumber(Integer addNumber) {
    this.addNumber = addNumber;
  }

  public LineForGoodsAdi sequentialNumber(Integer sequentialNumber) {
    this.sequentialNumber = sequentialNumber;
    return this;
  }

   /**
   * sequential item number for this adi, sequence number (1 to 999)
   * @return sequentialNumber
  **/
  @ApiModelProperty(example = "null", required = true, value = "sequential item number for this adi, sequence number (1 to 999)")
  public Integer getSequentialNumber() {
    return sequentialNumber;
  }

  public void setSequentialNumber(Integer sequentialNumber) {
    this.sequentialNumber = sequentialNumber;
  }

  public LineForGoodsAdi manufacturerCode(String manufacturerCode) {
    this.manufacturerCode = manufacturerCode;
    return this;
  }

   /**
   * Manufatorer erp internal code
   * @return manufacturerCode
  **/
  @ApiModelProperty(example = "null", required = true, value = "Manufatorer erp internal code")
  public String getManufacturerCode() {
    return manufacturerCode;
  }

  public void setManufacturerCode(String manufacturerCode) {
    this.manufacturerCode = manufacturerCode;
  }

  public LineForGoodsAdi adiDiscount(Double adiDiscount) {
    this.adiDiscount = adiDiscount;
    return this;
  }

   /**
   * This decimal 13 integers and 2 decimals, aditional adi discount
   * @return adiDiscount
  **/
  @ApiModelProperty(example = "null", value = "This decimal 13 integers and 2 decimals, aditional adi discount")
  public Double getAdiDiscount() {
    return adiDiscount;
  }

  public void setAdiDiscount(Double adiDiscount) {
    this.adiDiscount = adiDiscount;
  }

  public LineForGoodsAdi drawbackNumber(String drawbackNumber) {
    this.drawbackNumber = drawbackNumber;
    return this;
  }

   /**
   * Drawback number
   * @return drawbackNumber
  **/
  @ApiModelProperty(example = "null", value = "Drawback number")
  public String getDrawbackNumber() {
    return drawbackNumber;
  }

  public void setDrawbackNumber(String drawbackNumber) {
    this.drawbackNumber = drawbackNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LineForGoodsAdi lineForGoodsAdi = (LineForGoodsAdi) o;
    return Objects.equals(this.addNumber, lineForGoodsAdi.addNumber) &&
        Objects.equals(this.sequentialNumber, lineForGoodsAdi.sequentialNumber) &&
        Objects.equals(this.manufacturerCode, lineForGoodsAdi.manufacturerCode) &&
        Objects.equals(this.adiDiscount, lineForGoodsAdi.adiDiscount) &&
        Objects.equals(this.drawbackNumber, lineForGoodsAdi.drawbackNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addNumber, sequentialNumber, manufacturerCode, adiDiscount, drawbackNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LineForGoodsAdi {\n");
    
    sb.append("    addNumber: ").append(toIndentedString(addNumber)).append("\n");
    sb.append("    sequentialNumber: ").append(toIndentedString(sequentialNumber)).append("\n");
    sb.append("    manufacturerCode: ").append(toIndentedString(manufacturerCode)).append("\n");
    sb.append("    adiDiscount: ").append(toIndentedString(adiDiscount)).append("\n");
    sb.append("    drawbackNumber: ").append(toIndentedString(drawbackNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

