/**
 * BR16 - API
 * This documentation is about service accessories that will compose the product BR16, this services are essencial to maintenance and configuration of accounts
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * IssConfServiceList_taxRate_ibpt.h
 *
 * 
 */

#ifndef IssConfServiceList_taxRate_ibpt_H_
#define IssConfServiceList_taxRate_ibpt_H_


#include "ModelBase.h"


namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  IssConfServiceList_taxRate_ibpt
    : public ModelBase
{
public:
    IssConfServiceList_taxRate_ibpt();
    virtual ~IssConfServiceList_taxRate_ibpt();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// IssConfServiceList_taxRate_ibpt members

    /// <summary>
    /// 
    /// </summary>
    double getNationalFedTax() const;
    void setNationalFedTax(double value);
    bool nationalFedTaxIsSet() const;
    void unsetNationalFedTax();
    /// <summary>
    /// 
    /// </summary>
    double getCityTax() const;
    void setCityTax(double value);
    bool cityTaxIsSet() const;
    void unsetCityTax();

protected:
    double m_NationalFedTax;
    bool m_NationalFedTaxIsSet;
double m_CityTax;
    bool m_CityTaxIsSet;
};

}
}
}
}

#endif /* IssConfServiceList_taxRate_ibpt_H_ */
