/**
 * BR16 - API
 * This documentation is about service accessories that will compose the product BR16, this services are essencial to maintenance and configuration of accounts
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "PurchaseTransactionOut.h"

namespace io {
namespace swagger {
namespace client {
namespace model {

PurchaseTransactionOut::PurchaseTransactionOut()
{
    
}

PurchaseTransactionOut::~PurchaseTransactionOut()
{
}

void PurchaseTransactionOut::validate()
{
    // TODO: implement validation
}

web::json::value PurchaseTransactionOut::toJson() const
{
    web::json::value val = web::json::value::object();

    val[U("header")] = ModelBase::toJson(m_Header);
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Lines )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        val[U("lines")] = web::json::value::array(jsonArray);
            }
    val[U("calculatedTaxSummary")] = ModelBase::toJson(m_CalculatedTaxSummary);
    val[U("processingInfo")] = ModelBase::toJson(m_ProcessingInfo);
    

    return val;
}

void PurchaseTransactionOut::fromJson(web::json::value& val)
{
    std::shared_ptr<PurchaseHeaderOut> newHeader(new PurchaseHeaderOut());
    newHeader->fromJson(val[U("header")]);
    setHeader( newItem );
    {
        m_Lines.clear();
        std::vector<web::json::value> jsonArray;
                for( auto& item : val[U("lines")].as_array() )
        {
            
            if(item.is_null())
            {
                m_Lines.push_back( std::shared_ptr<PurchaseLinesOut>(nullptr) );
            }
            else
            {
                std::shared_ptr<PurchaseLinesOut> newItem(new PurchaseLinesOut());
                newItem->fromJson(item);
                m_Lines.push_back( newItem );
            }
            
        }
    }
    std::shared_ptr<PurchaseCalculatedTaxSummaryForService> newCalculatedTaxSummary(new PurchaseCalculatedTaxSummaryForService());
    newCalculatedTaxSummary->fromJson(val[U("calculatedTaxSummary")]);
    setCalculatedTaxSummary( newItem );
    std::shared_ptr<ProcessingInfo> newProcessingInfo(new ProcessingInfo());
    newProcessingInfo->fromJson(val[U("processingInfo")]);
    setProcessingInfo( newItem );
    
}

void PurchaseTransactionOut::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    m_Header->toMultipart(multipart, U("header."));
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Lines )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        multipart->add(ModelBase::toHttpContent(namePrefix + U("lines"), web::json::value::array(jsonArray), U("application/json")));
            }
    m_CalculatedTaxSummary->toMultipart(multipart, U("calculatedTaxSummary."));
    m_ProcessingInfo->toMultipart(multipart, U("processingInfo."));
    
}

void PurchaseTransactionOut::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    std::shared_ptr<PurchaseHeaderOut> newHeader(new PurchaseHeaderOut());
    newHeader->fromMultiPart(multipart, U("header."));
    setHeader( newHeader );
    {
        m_Lines.clear();
        
        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(U("lines"))));
        for( auto& item : jsonArray.as_array() )
        {
            
            if(item.is_null())
            {
                m_Lines.push_back( std::shared_ptr<PurchaseLinesOut>(nullptr) );
            }
            else
            {
                std::shared_ptr<PurchaseLinesOut> newItem(new PurchaseLinesOut());
                newItem->fromJson(item);
                m_Lines.push_back( newItem );
            }
            
        }
    }
    std::shared_ptr<PurchaseCalculatedTaxSummaryForService> newCalculatedTaxSummary(new PurchaseCalculatedTaxSummaryForService());
    newCalculatedTaxSummary->fromMultiPart(multipart, U("calculatedTaxSummary."));
    setCalculatedTaxSummary( newCalculatedTaxSummary );
    std::shared_ptr<ProcessingInfo> newProcessingInfo(new ProcessingInfo());
    newProcessingInfo->fromMultiPart(multipart, U("processingInfo."));
    setProcessingInfo( newProcessingInfo );
    
}


std::shared_ptr<PurchaseHeaderOut> PurchaseTransactionOut::getHeader() const
{
    return m_Header;
}
void PurchaseTransactionOut::setHeader(std::shared_ptr<PurchaseHeaderOut> value)
{
    m_Header = value;
    
}
std::vector<std::shared_ptr<PurchaseLinesOut>>& PurchaseTransactionOut::getLines()
{
    return m_Lines;
}
std::shared_ptr<PurchaseCalculatedTaxSummaryForService> PurchaseTransactionOut::getCalculatedTaxSummary() const
{
    return m_CalculatedTaxSummary;
}
void PurchaseTransactionOut::setCalculatedTaxSummary(std::shared_ptr<PurchaseCalculatedTaxSummaryForService> value)
{
    m_CalculatedTaxSummary = value;
    
}
std::shared_ptr<ProcessingInfo> PurchaseTransactionOut::getProcessingInfo() const
{
    return m_ProcessingInfo;
}
void PurchaseTransactionOut::setProcessingInfo(std::shared_ptr<ProcessingInfo> value)
{
    m_ProcessingInfo = value;
    
}

}
}
}
}

