/**
 * AvaTax Brazil
 * The Avatax-Brazil API exposes the most commonly services available for interacting with the AvaTax-Brazil services, allowing calculation of taxes, issuing electronic invoice documents and modifying existing transactions when allowed by tax authorities.  This API is exclusively for use by business with a physical presence in Brazil.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SalesHeaderIn_payment.h
 *
 * 
 */

#ifndef SalesHeaderIn_payment_H_
#define SalesHeaderIn_payment_H_


#include "ModelBase.h"

#include "PaymentTerms.h"
#include "SalesInstallmentIn.h"
#include <vector>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  SalesHeaderIn_payment
    : public ModelBase
{
public:
    SalesHeaderIn_payment();
    virtual ~SalesHeaderIn_payment();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SalesHeaderIn_payment members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<PaymentTerms> getTerms() const;
    void setTerms(std::shared_ptr<PaymentTerms> value);
    bool termsIsSet() const;
    void unsetTerms();
    /// <summary>
    /// installments
    /// </summary>
    std::vector<std::shared_ptr<SalesInstallmentIn>>& getInstallments();
    bool installmentsIsSet() const;
    void unsetInstallments();

protected:
    std::shared_ptr<PaymentTerms> m_Terms;
    bool m_TermsIsSet;
std::vector<std::shared_ptr<SalesInstallmentIn>> m_Installments;
    bool m_InstallmentsIsSet;
};

}
}
}
}

#endif /* SalesHeaderIn_payment_H_ */
