/**
 * BR16 - API
 * This documentation is about service accessories that will compose the product BR16, this services are essencial to maintenance and configuration of accounts
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SalesLinesOut_taxDeductions.h
 *
 * 
 */

#ifndef SalesLinesOut_taxDeductions_H_
#define SalesLinesOut_taxDeductions_H_


#include "ModelBase.h"


namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  SalesLinesOut_taxDeductions
    : public ModelBase
{
public:
    SalesLinesOut_taxDeductions();
    virtual ~SalesLinesOut_taxDeductions();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SalesLinesOut_taxDeductions members

    /// <summary>
    /// Deduction amount not ISS taxable. Example Building material
    /// </summary>
    double getIss() const;
    void setIss(double value);
    bool issIsSet() const;
    void unsetIss();

protected:
    double m_Iss;
    bool m_IssIsSet;
};

}
}
}
}

#endif /* SalesLinesOut_taxDeductions_H_ */
