/**
 * BR16 - API
 * This documentation is about service accessories that will compose the product BR16, this services are essencial to maintenance and configuration of accounts
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SalesTransactionIn.h
 *
 * 
 */

#ifndef SalesTransactionIn_H_
#define SalesTransactionIn_H_


#include "ModelBase.h"

#include "SalesHeaderIn.h"
#include "SalesLinesIn.h"
#include <vector>

namespace io {
namespace swagger {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  SalesTransactionIn
    : public ModelBase
{
public:
    SalesTransactionIn();
    virtual ~SalesTransactionIn();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SalesTransactionIn members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<SalesHeaderIn> getHeader() const;
    void setHeader(std::shared_ptr<SalesHeaderIn> value);
        /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<SalesLinesIn>>& getLines();
    
protected:
    std::shared_ptr<SalesHeaderIn> m_Header;
    std::vector<std::shared_ptr<SalesLinesIn>> m_Lines;
    };

}
}
}
}

#endif /* SalesTransactionIn_H_ */
