/**
 * AvaTax Brazil
 * The Avatax-Brazil API exposes the most commonly services available for interacting with the AvaTax-Brazil services, allowing calculation of taxes, issuing electronic invoice documents and modifying existing transactions when allowed by tax authorities.  This API is exclusively for use by business with a physical presence in Brazil.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AvaTaxBrazil) {
      root.AvaTaxBrazil = {};
    }
    root.AvaTaxBrazil.AdditionalInformationProcRef = factory(root.AvaTaxBrazil.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The AdditionalInformationProcRef model module.
   * @module model/AdditionalInformationProcRef
   * @version 1.0
   */

  /**
   * Constructs a new <code>AdditionalInformationProcRef</code>.
   * @alias module:model/AdditionalInformationProcRef
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>AdditionalInformationProcRef</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AdditionalInformationProcRef} obj Optional instance to populate.
   * @return {module:model/AdditionalInformationProcRef} The populated <code>AdditionalInformationProcRef</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('nProc')) {
        obj['nProc'] = ApiClient.convertToType(data['nProc'], 'String');
      }
      if (data.hasOwnProperty('indProc')) {
        obj['indProc'] = ApiClient.convertToType(data['indProc'], 'String');
      }
    }
    return obj;
  }

  /**
   * Process Identifier
   * @member {String} nProc
   */
  exports.prototype['nProc'] = undefined;
  /**
   * Process Origin - '0' # SEFAZ; - '1' # Justiça Federal; - '2' # Justiça Estadual; - '3' # Secex/RFB; - '9' # Outros 
   * @member {module:model/AdditionalInformationProcRef.IndProcEnum} indProc
   */
  exports.prototype['indProc'] = undefined;


  /**
   * Allowed values for the <code>indProc</code> property.
   * @enum {String}
   * @readonly
   */
  exports.IndProcEnum = {
    /**
     * value: "0"
     * @const
     */
    "0": "0",
    /**
     * value: "1"
     * @const
     */
    "1": "1",
    /**
     * value: "2"
     * @const
     */
    "2": "2",
    /**
     * value: "3"
     * @const
     */
    "3": "3",
    /**
     * value: "9"
     * @const
     */
    "9": "9"  };


  return exports;
}));


