/**
 * AvaTax Brazil
 * The Avatax-Brazil API exposes the most commonly services available for interacting with the AvaTax-Brazil services, allowing calculation of taxes, issuing electronic invoice documents and modifying existing transactions when allowed by tax authorities.  This API is exclusively for use by business with a physical presence in Brazil.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.AvaTaxBrazil) {
      root.AvaTaxBrazil = {};
    }
    root.AvaTaxBrazil.TaxType = factory(root.AvaTaxBrazil.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';


  /**
   * Enum class TaxType.
   * @enum {}
   * @readonly
   */
  var exports = {
    /**
     * value: "INSS"
     * @const
     */
    "INSS": "INSS",
    /**
     * value: "INSS_RF"
     * @const
     */
    "INSS_RF": "INSS_RF",
    /**
     * value: "INSS_AR"
     * @const
     */
    "INSS_AR": "INSS_AR",
    /**
     * value: "IRRF"
     * @const
     */
    "IRRF": "IRRF",
    /**
     * value: "PIS"
     * @const
     */
    "PIS": "PIS",
    /**
     * value: "PIS_RF"
     * @const
     */
    "PIS_RF": "PIS_RF",
    /**
     * value: "PIS_RP"
     * @const
     */
    "PIS_RP": "PIS_RP",
    /**
     * value: "PIS_PP"
     * @const
     */
    "PIS_PP": "PIS_PP",
    /**
     * value: "COFINS"
     * @const
     */
    "COFINS": "COFINS",
    /**
     * value: "COFINS_RF"
     * @const
     */
    "COFINS_RF": "COFINS_RF",
    /**
     * value: "COFINS_RP"
     * @const
     */
    "COFINS_RP": "COFINS_RP",
    /**
     * value: "COFINS_PP"
     * @const
     */
    "COFINS_PP": "COFINS_PP",
    /**
     * value: "CSLL"
     * @const
     */
    "CSLL": "CSLL",
    /**
     * value: "CSLL_RF"
     * @const
     */
    "CSLL_RF": "CSLL_RF",
    /**
     * value: "CSLL_PP"
     * @const
     */
    "CSLL_PP": "CSLL_PP",
    /**
     * value: "CSLL_RP"
     * @const
     */
    "CSLL_RP": "CSLL_RP",
    /**
     * value: "IRPJ"
     * @const
     */
    "IRPJ": "IRPJ",
    /**
     * value: "ISS"
     * @const
     */
    "ISS": "ISS",
    /**
     * value: "ISS_RF"
     * @const
     */
    "ISS_RF": "ISS_RF",
    /**
     * value: "IPI"
     * @const
     */
    "IPI": "IPI"  };

  /**
   * Returns a <code>TaxType</code> enum value from a Javascript object name.
   * @param {Object} data The plain JavaScript object containing the name of the enum value.
   * @return {module:model/TaxType} The enum <code>TaxType</code> value.
   */
  exports.constructFromObject = function(object) {
    return exports[object];
  }

  return exports;
}));


