//
// AgastWithholdingCSLL.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** inform if this item is subject to withholding CSLL on service Transactions, by entity type, default true */
open class AgastWithholdingCSLL: JSONEncodable {
    public var legalReason: String?
    public var business: Bool?
    /** reference id to TaxLegalReason */
    public var businessLegalReason: String?
    public var federalGovernment: Bool?
    /** reference id to TaxLegalReason */
    public var federalGovernmentLegalReason: String?
    public var stateGovernment: Bool?
    /** reference id to TaxLegalReason */
    public var stateGovernmentLegalReason: String?
    public var cityGovernment: Bool?
    /** reference id to TaxLegalReason */
    public var cityGovernmentLegalReason: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["legalReason"] = self.legalReason
        nillableDictionary["business"] = self.business
        nillableDictionary["businessLegalReason"] = self.businessLegalReason
        nillableDictionary["federalGovernment"] = self.federalGovernment
        nillableDictionary["federalGovernmentLegalReason"] = self.federalGovernmentLegalReason
        nillableDictionary["stateGovernment"] = self.stateGovernment
        nillableDictionary["stateGovernmentLegalReason"] = self.stateGovernmentLegalReason
        nillableDictionary["cityGovernment"] = self.cityGovernment
        nillableDictionary["cityGovernmentLegalReason"] = self.cityGovernmentLegalReason
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
