//
// EntityInformerForGoodsFederalTaxRegime.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class EntityInformerForGoodsFederalTaxRegime: JSONEncodable {
    public var code: String?
    public var name: String?
    public var abbr: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["code"] = self.code
        nillableDictionary["name"] = self.name
        nillableDictionary["abbr"] = self.abbr
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
