//
// SefazInvoiceStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class SefazInvoiceStatus: JSONEncodable {
    public enum Environment: String { 
        case 1 = "1"
        case 2 = "2"
    }
    public var code: String?
    public var desc: String?
    public var _protocol: String?
    public var rec: String?
    public var date: Date?
    /** - &#39;1&#39; # Ambiente de Produção - &#39;2&#39; # Ambiente de Homologação  */
    public var environment: Environment?
    public var appVersion: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["code"] = self.code
        nillableDictionary["desc"] = self.desc
        nillableDictionary["protocol"] = self._protocol
        nillableDictionary["rec"] = self.rec
        nillableDictionary["date"] = self.date?.encodeToJSON()
        nillableDictionary["environment"] = self.environment?.rawValue
        nillableDictionary["appVersion"] = self.appVersion
        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
