//
// LocationSecondaryStateTaxId.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class LocationSecondaryStateTaxId: JSONEncodable {
    public var stateTaxId: String?
    public var state: StateEnum?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["stateTaxId"] = self.stateTaxId
        nillableDictionary["state"] = self.state?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
