//
// SimpleAddress.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class SimpleAddress: JSONEncodable {
    /** Address */
    public var line1: String?
    /** Number */
    public var line2: String?
    /** District */
    public var line3: String?
    public var city: String?
    /** Brazilian Zip Code */
    public var zipcode: String?
    public var state: StateEnum?
    /** Use ISO 3166-1 alpha-3 codes */
    public var country: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["line1"] = self.line1
        nillableDictionary["line2"] = self.line2
        nillableDictionary["line3"] = self.line3
        nillableDictionary["city"] = self.city
        nillableDictionary["zipcode"] = self.zipcode
        nillableDictionary["state"] = self.state?.encodeToJSON()
        nillableDictionary["country"] = self.country
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
