/* 
 * BR16 - API
 *
 * This documentation is about service accessories that will compose the product BR16, this services are essencial to maintenance and configuration of accounts
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AgastExtendForSefaz
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AgastExtendForSefazTests
    {
        // TODO uncomment below to declare an instance variable for AgastExtendForSefaz
        //private AgastExtendForSefaz instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AgastExtendForSefaz
            //instance = new AgastExtendForSefaz();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AgastExtendForSefaz
        /// </summary>
        [Test]
        public void AgastExtendForSefazInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AgastExtendForSefaz
            //Assert.IsInstanceOfType<AgastExtendForSefaz> (instance, "variable 'instance' is a AgastExtendForSefaz");
        }

        /// <summary>
        /// Test the property 'HsCode'
        /// </summary>
        [Test]
        public void HsCodeTest()
        {
            // TODO unit test for the property 'HsCode'
        }
        /// <summary>
        /// Test the property 'Ex'
        /// </summary>
        [Test]
        public void ExTest()
        {
            // TODO unit test for the property 'Ex'
        }
        /// <summary>
        /// Test the property 'Cest'
        /// </summary>
        [Test]
        public void CestTest()
        {
            // TODO unit test for the property 'Cest'
        }
        /// <summary>
        /// Test the property 'Cean'
        /// </summary>
        [Test]
        public void CeanTest()
        {
            // TODO unit test for the property 'Cean'
        }
        /// <summary>
        /// Test the property 'Nve'
        /// </summary>
        [Test]
        public void NveTest()
        {
            // TODO unit test for the property 'Nve'
        }
        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Test]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }
        /// <summary>
        /// Test the property 'UnitTaxable'
        /// </summary>
        [Test]
        public void UnitTaxableTest()
        {
            // TODO unit test for the property 'UnitTaxable'
        }
        /// <summary>
        /// Test the property 'NFCI'
        /// </summary>
        [Test]
        public void NFCITest()
        {
            // TODO unit test for the property 'NFCI'
        }

    }

}
