/* 
 * BR16 - API
 *
 * This documentation is about service accessories that will compose the product BR16, this services are essencial to maintenance and configuration of accounts
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LineForGoodsIndExport
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LineForGoodsIndExportTests
    {
        // TODO uncomment below to declare an instance variable for LineForGoodsIndExport
        //private LineForGoodsIndExport instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LineForGoodsIndExport
            //instance = new LineForGoodsIndExport();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LineForGoodsIndExport
        /// </summary>
        [Test]
        public void LineForGoodsIndExportInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LineForGoodsIndExport
            //Assert.IsInstanceOfType<LineForGoodsIndExport> (instance, "variable 'instance' is a LineForGoodsIndExport");
        }

        /// <summary>
        /// Test the property 'RegisterNumber'
        /// </summary>
        [Test]
        public void RegisterNumberTest()
        {
            // TODO unit test for the property 'RegisterNumber'
        }
        /// <summary>
        /// Test the property 'AccessKey'
        /// </summary>
        [Test]
        public void AccessKeyTest()
        {
            // TODO unit test for the property 'AccessKey'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }

    }

}
