/* 
 * BR16 - API
 *
 * This documentation is about service accessories that will compose the product BR16, this services are essencial to maintenance and configuration of accounts
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing NRef
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NRefTests
    {
        // TODO uncomment below to declare an instance variable for NRef
        //private NRef instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NRef
            //instance = new NRef();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NRef
        /// </summary>
        [Test]
        public void NRefInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NRef
            //Assert.IsInstanceOfType<NRef> (instance, "variable 'instance' is a NRef");
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'RefNFe'
        /// </summary>
        [Test]
        public void RefNFeTest()
        {
            // TODO unit test for the property 'RefNFe'
        }
        /// <summary>
        /// Test the property 'RefCTe'
        /// </summary>
        [Test]
        public void RefCTeTest()
        {
            // TODO unit test for the property 'RefCTe'
        }
        /// <summary>
        /// Test the property 'RefECF'
        /// </summary>
        [Test]
        public void RefECFTest()
        {
            // TODO unit test for the property 'RefECF'
        }
        /// <summary>
        /// Test the property 'RefNF'
        /// </summary>
        [Test]
        public void RefNFTest()
        {
            // TODO unit test for the property 'RefNF'
        }
        /// <summary>
        /// Test the property 'RefFarmerNF'
        /// </summary>
        [Test]
        public void RefFarmerNFTest()
        {
            // TODO unit test for the property 'RefFarmerNF'
        }

    }

}
