/* 
 * AvaTax Brazil
 *
 * The Avatax-Brazil API exposes the most commonly services available for interacting with the AvaTax-Brazil services, allowing calculation of taxes, issuing electronic invoice documents and modifying existing transactions when allowed by tax authorities.  This API is exclusively for use by business with a physical presence in Brazil.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing PaymentTaxByType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PaymentTaxByTypeTests
    {
        // TODO uncomment below to declare an instance variable for PaymentTaxByType
        //private PaymentTaxByType instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PaymentTaxByType
            //instance = new PaymentTaxByType();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PaymentTaxByType
        /// </summary>
        [Test]
        public void PaymentTaxByTypeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PaymentTaxByType
            //Assert.IsInstanceOfType<PaymentTaxByType> (instance, "variable 'instance' is a PaymentTaxByType");
        }

        /// <summary>
        /// Test the property 'Irrf'
        /// </summary>
        [Test]
        public void IrrfTest()
        {
            // TODO unit test for the property 'Irrf'
        }
        /// <summary>
        /// Test the property 'InssRf'
        /// </summary>
        [Test]
        public void InssRfTest()
        {
            // TODO unit test for the property 'InssRf'
        }
        /// <summary>
        /// Test the property 'IssRf'
        /// </summary>
        [Test]
        public void IssRfTest()
        {
            // TODO unit test for the property 'IssRf'
        }
        /// <summary>
        /// Test the property 'PisRf'
        /// </summary>
        [Test]
        public void PisRfTest()
        {
            // TODO unit test for the property 'PisRf'
        }
        /// <summary>
        /// Test the property 'CofinsRf'
        /// </summary>
        [Test]
        public void CofinsRfTest()
        {
            // TODO unit test for the property 'CofinsRf'
        }
        /// <summary>
        /// Test the property 'CsllRf'
        /// </summary>
        [Test]
        public void CsllRfTest()
        {
            // TODO unit test for the property 'CsllRf'
        }

    }

}
