/* 
 * BR16 - API
 *
 * This documentation is about service accessories that will compose the product BR16, this services are essencial to maintenance and configuration of accounts
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing SalesCalculatedTaxSummaryForService
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SalesCalculatedTaxSummaryForServiceTests
    {
        // TODO uncomment below to declare an instance variable for SalesCalculatedTaxSummaryForService
        //private SalesCalculatedTaxSummaryForService instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SalesCalculatedTaxSummaryForService
            //instance = new SalesCalculatedTaxSummaryForService();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SalesCalculatedTaxSummaryForService
        /// </summary>
        [Test]
        public void SalesCalculatedTaxSummaryForServiceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SalesCalculatedTaxSummaryForService
            //Assert.IsInstanceOfType<SalesCalculatedTaxSummaryForService> (instance, "variable 'instance' is a SalesCalculatedTaxSummaryForService");
        }

        /// <summary>
        /// Test the property 'NumberOfLines'
        /// </summary>
        [Test]
        public void NumberOfLinesTest()
        {
            // TODO unit test for the property 'NumberOfLines'
        }
        /// <summary>
        /// Test the property 'Subtotal'
        /// </summary>
        [Test]
        public void SubtotalTest()
        {
            // TODO unit test for the property 'Subtotal'
        }
        /// <summary>
        /// Test the property 'TotalTax'
        /// </summary>
        [Test]
        public void TotalTaxTest()
        {
            // TODO unit test for the property 'TotalTax'
        }
        /// <summary>
        /// Test the property 'GrandTotal'
        /// </summary>
        [Test]
        public void GrandTotalTest()
        {
            // TODO unit test for the property 'GrandTotal'
        }
        /// <summary>
        /// Test the property 'TaxByType'
        /// </summary>
        [Test]
        public void TaxByTypeTest()
        {
            // TODO unit test for the property 'TaxByType'
        }

    }

}
