# coding: utf-8

"""
    AvaTax Brazil

    The Avatax-Brazil API exposes the most commonly services available for interacting with the AvaTax-Brazil services, allowing calculation of taxes, issuing electronic invoice documents and modifying existing transactions when allowed by tax authorities.  This API is exclusively for use by business with a physical presence in Brazil.

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ItemCpom(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, company_id=None, city_code=None, item_code=None, code=None):
        """
        ItemCpom - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'company_id': 'str',
            'city_code': 'str',
            'item_code': 'str',
            'code': 'str'
        }

        self.attribute_map = {
            'company_id': 'companyId',
            'city_code': 'cityCode',
            'item_code': 'itemCode',
            'code': 'code'
        }

        self._company_id = company_id
        self._city_code = city_code
        self._item_code = item_code
        self._code = code

    @property
    def company_id(self):
        """
        Gets the company_id of this ItemCpom.
        Company ID

        :return: The company_id of this ItemCpom.
        :rtype: str
        """
        return self._company_id

    @company_id.setter
    def company_id(self, company_id):
        """
        Sets the company_id of this ItemCpom.
        Company ID

        :param company_id: The company_id of this ItemCpom.
        :type: str
        """
        if company_id is None:
            raise ValueError("Invalid value for `company_id`, must not be `None`")

        self._company_id = company_id

    @property
    def city_code(self):
        """
        Gets the city_code of this ItemCpom.
        IBGE city code

        :return: The city_code of this ItemCpom.
        :rtype: str
        """
        return self._city_code

    @city_code.setter
    def city_code(self, city_code):
        """
        Sets the city_code of this ItemCpom.
        IBGE city code

        :param city_code: The city_code of this ItemCpom.
        :type: str
        """
        if city_code is None:
            raise ValueError("Invalid value for `city_code`, must not be `None`")
        if city_code is not None and not re.search('[0-9]{7}', city_code):
            raise ValueError("Invalid value for `city_code`, must be a follow pattern or equal to `/[0-9]{7}/`")

        self._city_code = city_code

    @property
    def item_code(self):
        """
        Gets the item_code of this ItemCpom.
        ERP Code

        :return: The item_code of this ItemCpom.
        :rtype: str
        """
        return self._item_code

    @item_code.setter
    def item_code(self, item_code):
        """
        Sets the item_code of this ItemCpom.
        ERP Code

        :param item_code: The item_code of this ItemCpom.
        :type: str
        """
        if item_code is None:
            raise ValueError("Invalid value for `item_code`, must not be `None`")
        if item_code is not None and len(item_code) > 60:
            raise ValueError("Invalid value for `item_code`, length must be less than or equal to `60`")

        self._item_code = item_code

    @property
    def code(self):
        """
        Gets the code of this ItemCpom.
        Code in City

        :return: The code of this ItemCpom.
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """
        Sets the code of this ItemCpom.
        Code in City

        :param code: The code of this ItemCpom.
        :type: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")

        self._code = code

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
