# coding: utf-8

"""
    BR16 - API

    This documentation is about service accessories that will compose the product BR16, this services are essencial to maintenance and configuration of accounts

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PayRecLinesOut(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, line_code=None, line_type=None, item_code=None, item_description=None, item_doc_number=None, line_untaxed_penality=None, line_untaxed_discount=None, line_amount=None, line_net_value=None, withholding_mode=None, calculated_tax=None):
        """
        PayRecLinesOut - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'line_code': 'int',
            'line_type': 'str',
            'item_code': 'str',
            'item_description': 'str',
            'item_doc_number': 'str',
            'line_untaxed_penality': 'float',
            'line_untaxed_discount': 'float',
            'line_amount': 'float',
            'line_net_value': 'float',
            'withholding_mode': 'WithholdingMode',
            'calculated_tax': 'PaymentCalculatedTax'
        }

        self.attribute_map = {
            'line_code': 'lineCode',
            'line_type': 'lineType',
            'item_code': 'itemCode',
            'item_description': 'itemDescription',
            'item_doc_number': 'itemDocNumber',
            'line_untaxed_penality': 'lineUntaxedPenality',
            'line_untaxed_discount': 'lineUntaxedDiscount',
            'line_amount': 'lineAmount',
            'line_net_value': 'lineNetValue',
            'withholding_mode': 'withholdingMode',
            'calculated_tax': 'calculatedTax'
        }

        self._line_code = line_code
        self._line_type = line_type
        self._item_code = item_code
        self._item_description = item_description
        self._item_doc_number = item_doc_number
        self._line_untaxed_penality = line_untaxed_penality
        self._line_untaxed_discount = line_untaxed_discount
        self._line_amount = line_amount
        self._line_net_value = line_net_value
        self._withholding_mode = withholding_mode
        self._calculated_tax = calculated_tax

    @property
    def line_code(self):
        """
        Gets the line_code of this PayRecLinesOut.
        Installment number in this document

        :return: The line_code of this PayRecLinesOut.
        :rtype: int
        """
        return self._line_code

    @line_code.setter
    def line_code(self, line_code):
        """
        Sets the line_code of this PayRecLinesOut.
        Installment number in this document

        :param line_code: The line_code of this PayRecLinesOut.
        :type: int
        """

        self._line_code = line_code

    @property
    def line_type(self):
        """
        Gets the line_type of this PayRecLinesOut.

        :return: The line_type of this PayRecLinesOut.
        :rtype: str
        """
        return self._line_type

    @line_type.setter
    def line_type(self, line_type):
        """
        Sets the line_type of this PayRecLinesOut.

        :param line_type: The line_type of this PayRecLinesOut.
        :type: str
        """
        allowed_values = ["installment"]
        if line_type not in allowed_values:
            raise ValueError(
                "Invalid value for `line_type` ({0}), must be one of {1}"
                .format(line_type, allowed_values)
            )

        self._line_type = line_type

    @property
    def item_code(self):
        """
        Gets the item_code of this PayRecLinesOut.
        Bill transaction code This string is a code maintained by the client application to uniquely identify a document in the client's systems. It will typically be an invoice number, sales order, receipt number, returned merchandise authorization number, etc.

        :return: The item_code of this PayRecLinesOut.
        :rtype: str
        """
        return self._item_code

    @item_code.setter
    def item_code(self, item_code):
        """
        Sets the item_code of this PayRecLinesOut.
        Bill transaction code This string is a code maintained by the client application to uniquely identify a document in the client's systems. It will typically be an invoice number, sales order, receipt number, returned merchandise authorization number, etc.

        :param item_code: The item_code of this PayRecLinesOut.
        :type: str
        """
        if item_code is None:
            raise ValueError("Invalid value for `item_code`, must not be `None`")

        self._item_code = item_code

    @property
    def item_description(self):
        """
        Gets the item_description of this PayRecLinesOut.
        Free description about this payment

        :return: The item_description of this PayRecLinesOut.
        :rtype: str
        """
        return self._item_description

    @item_description.setter
    def item_description(self, item_description):
        """
        Sets the item_description of this PayRecLinesOut.
        Free description about this payment

        :param item_description: The item_description of this PayRecLinesOut.
        :type: str
        """

        self._item_description = item_description

    @property
    def item_doc_number(self):
        """
        Gets the item_doc_number of this PayRecLinesOut.
        Installment number, when paid AS IS

        :return: The item_doc_number of this PayRecLinesOut.
        :rtype: str
        """
        return self._item_doc_number

    @item_doc_number.setter
    def item_doc_number(self, item_doc_number):
        """
        Sets the item_doc_number of this PayRecLinesOut.
        Installment number, when paid AS IS

        :param item_doc_number: The item_doc_number of this PayRecLinesOut.
        :type: str
        """

        self._item_doc_number = item_doc_number

    @property
    def line_untaxed_penality(self):
        """
        Gets the line_untaxed_penality of this PayRecLinesOut.
        Penalty, usually because paid after due date

        :return: The line_untaxed_penality of this PayRecLinesOut.
        :rtype: float
        """
        return self._line_untaxed_penality

    @line_untaxed_penality.setter
    def line_untaxed_penality(self, line_untaxed_penality):
        """
        Sets the line_untaxed_penality of this PayRecLinesOut.
        Penalty, usually because paid after due date

        :param line_untaxed_penality: The line_untaxed_penality of this PayRecLinesOut.
        :type: float
        """

        self._line_untaxed_penality = line_untaxed_penality

    @property
    def line_untaxed_discount(self):
        """
        Gets the line_untaxed_discount of this PayRecLinesOut.
        unconditional discounts

        :return: The line_untaxed_discount of this PayRecLinesOut.
        :rtype: float
        """
        return self._line_untaxed_discount

    @line_untaxed_discount.setter
    def line_untaxed_discount(self, line_untaxed_discount):
        """
        Sets the line_untaxed_discount of this PayRecLinesOut.
        unconditional discounts

        :param line_untaxed_discount: The line_untaxed_discount of this PayRecLinesOut.
        :type: float
        """

        self._line_untaxed_discount = line_untaxed_discount

    @property
    def line_amount(self):
        """
        Gets the line_amount of this PayRecLinesOut.
        GrossAmount of this installment line

        :return: The line_amount of this PayRecLinesOut.
        :rtype: float
        """
        return self._line_amount

    @line_amount.setter
    def line_amount(self, line_amount):
        """
        Sets the line_amount of this PayRecLinesOut.
        GrossAmount of this installment line

        :param line_amount: The line_amount of this PayRecLinesOut.
        :type: float
        """

        self._line_amount = line_amount

    @property
    def line_net_value(self):
        """
        Gets the line_net_value of this PayRecLinesOut.
        Net value, the net Value is Gross value plus penalty minus sum of discount and withhold taxes

        :return: The line_net_value of this PayRecLinesOut.
        :rtype: float
        """
        return self._line_net_value

    @line_net_value.setter
    def line_net_value(self, line_net_value):
        """
        Sets the line_net_value of this PayRecLinesOut.
        Net value, the net Value is Gross value plus penalty minus sum of discount and withhold taxes

        :param line_net_value: The line_net_value of this PayRecLinesOut.
        :type: float
        """

        self._line_net_value = line_net_value

    @property
    def withholding_mode(self):
        """
        Gets the withholding_mode of this PayRecLinesOut.
        x is because not subject of this tax independent of Threshold

        :return: The withholding_mode of this PayRecLinesOut.
        :rtype: WithholdingMode
        """
        return self._withholding_mode

    @withholding_mode.setter
    def withholding_mode(self, withholding_mode):
        """
        Sets the withholding_mode of this PayRecLinesOut.
        x is because not subject of this tax independent of Threshold

        :param withholding_mode: The withholding_mode of this PayRecLinesOut.
        :type: WithholdingMode
        """

        self._withholding_mode = withholding_mode

    @property
    def calculated_tax(self):
        """
        Gets the calculated_tax of this PayRecLinesOut.

        :return: The calculated_tax of this PayRecLinesOut.
        :rtype: PaymentCalculatedTax
        """
        return self._calculated_tax

    @calculated_tax.setter
    def calculated_tax(self, calculated_tax):
        """
        Sets the calculated_tax of this PayRecLinesOut.

        :param calculated_tax: The calculated_tax of this PayRecLinesOut.
        :type: PaymentCalculatedTax
        """

        self._calculated_tax = calculated_tax

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
