<?php
/**
 * PurchaseCalculatedTaxSummaryForServiceTaxByTypeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AvaTax Brazil
 *
 * The Avatax-Brazil API exposes the most commonly services available for interacting with the AvaTax-Brazil services, allowing calculation of taxes, issuing electronic invoice documents and modifying existing transactions when allowed by tax authorities.  This API is exclusively for use by business with a physical presence in Brazil.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * PurchaseCalculatedTaxSummaryForServiceTaxByTypeTest Class Doc Comment
 *
 * @category    Class */
// * @description Object with summary of all taxes returned by engine
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PurchaseCalculatedTaxSummaryForServiceTaxByTypeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "PurchaseCalculatedTaxSummaryForServiceTaxByType"
     */
    public function testPurchaseCalculatedTaxSummaryForServiceTaxByType()
    {

    }

    /**
     * Test attribute "iss_rf"
     */
    public function testPropertyIssRf()
    {

    }

    /**
     * Test attribute "pis_rf"
     */
    public function testPropertyPisRf()
    {

    }

    /**
     * Test attribute "cofins_rf"
     */
    public function testPropertyCofinsRf()
    {

    }

    /**
     * Test attribute "csll_rf"
     */
    public function testPropertyCsllRf()
    {

    }

    /**
     * Test attribute "irrf"
     */
    public function testPropertyIrrf()
    {

    }

    /**
     * Test attribute "inss_rf"
     */
    public function testPropertyInssRf()
    {

    }

    /**
     * Test attribute "inss_ar"
     */
    public function testPropertyInssAr()
    {

    }

    /**
     * Test attribute "pis"
     */
    public function testPropertyPis()
    {

    }

    /**
     * Test attribute "cofins"
     */
    public function testPropertyCofins()
    {

    }

}
