<?php
/**
 * CSTTableBEnum
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * AvaTax Brazil
 *
 * The Avatax-Brazil API exposes the most commonly services available for interacting with the AvaTax-Brazil services, allowing calculation of taxes, issuing electronic invoice documents and modifying existing transactions when allowed by tax authorities.  This API is exclusively for use by business with a physical presence in Brazil.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * CSTTableBEnum Class Doc Comment
 *
 * @category    Class */
 // @description Use to determined how the tax is applicable and calculated. It may define and exemption, a tax base reduction, identify that a special rate is applicable (not the rate itself). - &#39;00&#39; # Taxed in its totality - &#39;10&#39; # Taxed and subject to tax substitution (ICMS ST) - &#39;20&#39; # Taxed with Tax Base Reduction - &#39;30&#39; # Exempt /Not Taxed and subject to tax Substitution (ICMS#ST) - &#39;40&#39; # Tax Exempt - &#39;41&#39; # Not Taxed - &#39;50&#39; # Taxes Suspended - &#39;51&#39; # Taxes Diferred - &#39;60&#39; # ICMS Tax already collected through Substituition (ICMS ST) - &#39;70&#39; # Taxed with Tax Base Reduction and subject to Tax Subsititution (ICMS ST) - &#39;90&#39; # Others
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CSTTableBEnum {
    const _00 = '00';
    const _10 = '10';
    const _20 = '20';
    const _30 = '30';
    const _40 = '40';
    const _41 = '41';
    const _50 = '50';
    const _51 = '51';
    const _60 = '60';
    const _70 = '70';
    const _90 = '90';
    

    
}

