<?php
/**
 * CSTTableAEnum
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * BR16 - API
 *
 * This documentation is about service accessories that will compose the product BR16, this services are essencial to maintenance and configuration of accounts
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * CSTTableAEnum Class Doc Comment
 *
 * @category    Class */
 // @description Source of product or merchandise, - &#39;0&#39; # National goods - &#39;except those treated in codes 3,4, 5 and 8 - &#39;1&#39; # Imported directly by seller, except those in code 6 - &#39;2&#39; # Foreign goods - &#39;Acquired in the internal market (inside Brazil), except those in code 7 - &#39;3&#39; # Merchandise or goods with imported content above 40% and with less than or equal to 70% - &#39;4&#39; # National goods from production following &#39;standard basic processes&#39; as stablished by legislation (standard basic processes are devised to separate simple assembly from manufaturing processes) - &#39;5&#39; # National goods - &#39;Merchandise or goods with imported content equal or below 40% - &#39;6&#39; # Foreign goods - &#39;Directly imported by Seller, without a National Equivalent as listed by Comex and natural gas - &#39;7&#39; # Foreign goods - &#39;Acquired inside Brazil, without a National Equivalent  as listed by Comex and natural gas - &#39;8&#39; # Merchandise or goods with imported content above 70%
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CSTTableAEnum {
    const _0 = '0';
    const _1 = '1';
    const _2 = '2';
    const _3 = '3';
    const _4 = '4';
    const _5 = '5';
    const _6 = '6';
    const _7 = '7';
    const _8 = '8';
    

    
}

