/* 
 * AvaTax Brazil
 *
 * The Avatax-Brazil API exposes the most commonly services available for interacting with the AvaTax-Brazil services, allowing calculation of taxes, issuing electronic invoice documents and modifying existing transactions when allowed by tax authorities.  This API is exclusively for use by business with a physical presence in Brazil.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

// inform if this item is subject to withholding tax on service Transactions, default true
type AgastWithholding struct {

	IRRF bool `json:"IRRF,omitempty"`

	// reference id to TaxLegalReason
	IRRFLegalReason string `json:"IRRFLegalReason,omitempty"`

	// Item subjecto to payroll discharge Item sujeto à desoneraçãode folha de pagamento 
	INSSSubjectToDischarge bool `json:"INSSSubjectToDischarge,omitempty"`

	INSS bool `json:"INSS,omitempty"`

	// reference id to TaxLegalReason
	INSSLegalReason string `json:"INSSLegalReason,omitempty"`

	INSsForSimples bool `json:"INSsForSimples,omitempty"`

	// reference id to TaxLegalReason
	INSSForSimplesLegalReason string `json:"INSSForSimplesLegalReason,omitempty"`

	PIS AgastWithholdingPis `json:"PIS,omitempty"`

	COFINS AgastWithholdingCofins `json:"COFINS,omitempty"`

	CSLL AgastWithholdingCsll `json:"CSLL,omitempty"`
}
