/* 
 * BR16 - API
 *
 * This documentation is about service accessories that will compose the product BR16, this services are essencial to maintenance and configuration of accounts
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type IpbtConfItem struct {

	State StateEnum `json:"state,omitempty"`

	FederalTax float64 `json:"federalTax,omitempty"`

	ImportTax float64 `json:"importTax,omitempty"`

	StateTax float64 `json:"stateTax,omitempty"`

	CityTax float64 `json:"cityTax,omitempty"`

	Source string `json:"source,omitempty"`
}
