/* 
 * BR16 - API
 *
 * This documentation is about service accessories that will compose the product BR16, this services are essencial to maintenance and configuration of accounts
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type IssConfServiceListTaxRate struct {

	ISS ServiceItemTaxRate `json:"ISS,omitempty"`

	ISS_RF ServiceItemTaxRate `json:"ISS_RF,omitempty"`

	ISS_E ServiceItemTaxRate `json:"ISS_E,omitempty"`

	ISS_I ServiceItemTaxRate `json:"ISS_I,omitempty"`

	Ibpt IssConfServiceListTaxRateIbpt `json:"ibpt,omitempty"`
}
