/* 
 * BR16 - API
 *
 * This documentation is about service accessories that will compose the product BR16, this services are essencial to maintenance and configuration of accounts
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type PayRecCalculatedTaxSummaryForService struct {

	// Count of lines
	NumberOfLines int32 `json:"numberOfLines,omitempty"`

	// Sum of grossvalues
	Subtotal float64 `json:"subtotal,omitempty"`

	// Sum of all withholding values
	TotalTax float64 `json:"totalTax,omitempty"`

	// Sum all NetValues
	GrandTotal float64 `json:"grandTotal,omitempty"`

	PccWithholdingModes []PccWithholdingMode `json:"pccWithholdingModes,omitempty"`

	TaxByType PayRecCalculatedTaxSummaryForServiceTaxByType `json:"taxByType,omitempty"`
}
