/* 
 * AvaTax Brazil
 *
 * The Avatax-Brazil API exposes the most commonly services available for interacting with the AvaTax-Brazil services, allowing calculation of taxes, issuing electronic invoice documents and modifying existing transactions when allowed by tax authorities.  This API is exclusively for use by business with a physical presence in Brazil.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type PurchaseTaxesConfig struct {

	// ATTENTION SELLER POINT OF VIEW. There are cases where both Seller, Buyer and items are taxable but a special situation still exists that forces the transaction to be exempt specially for PIS and COFINS.  This attribute will allow users to identify such scenarios and trigger the exemption in spite of all other settings. T TAXABLE, N NOT TAXABLE, Z TAXABLE WITH RATE=0.00, E EXEMPT, H SUSPENDED, S SPECIFIC RATE - 'T' # TAXABLE - 'N' # NOT TAXABLE - 'Z' # TAXABLE WITH RATE=0.00 - 'E' # EXEMPT - 'H' # SUSPENDED - 'S' # SPECIFIC RATE 
	EntityAccruableCOFINSTaxation string `json:"entityAccruableCOFINSTaxation,omitempty"`

	// ATTENTION SELLER POINT OF VIEW. There are cases where both Seller, Buyer and items are taxable but a special situation still exists that forces the transaction to be CSLL exempt.   This attribute will allow users to identify such scenarios and trigger the exemption in spite of all other settings.  - T TAXABLE - E EXEMPT 
	EntityAccruableCSLLTaxation string `json:"entityAccruableCSLLTaxation,omitempty"`

	// ATTENTION SELLER POINT OF VIEW. There are cases where both Seller, Buyer and items are taxable but a special situation still exists that forces the transaction to be exempt specially for PIS and COFINS.  This attribute will allow users to identify such scenarios and trigger the exemption in spite of all other settings. T TAXABLE, N NOT TAXABLE, Z TAXABLE WITH RATE=0.00, E EXEMPT, H SUSPENDED, S SPECIFIC RATE - 'T' # TAXABLE - 'N' # NOT TAXABLE - 'Z' # TAXABLE WITH RATE=0.00 - 'E' # EXEMPT - 'H' # SUSPENDED - 'S' # SPECIFIC RATE 
	EntityAccruablePISTaxation string `json:"entityAccruablePISTaxation,omitempty"`

	// This is a code available by Receita Federal for reason of the exemption, When Code is 999 the User system need send the custom reason to Exemption. When not Taxable of Seller point of view this field has the reason code.
	AccruableCOFINSExempCodeTaxation string `json:"accruableCOFINSExempCodeTaxation,omitempty"`

	// This is a code available by Receita Federal for reason of the exemption, When Code is 999 the User system need send the custom reason to Exemption. When not Taxable of Seller point of view this field has the reason code.
	AccruablePISExempCodeTaxation string `json:"accruablePISExempCodeTaxation,omitempty"`

	// When Code is 999 the user system need send the custom reason to Exemption
	AccruablePISExemptReasonTaxation string `json:"accruablePISExemptReasonTaxation,omitempty"`

	// When Code is 999 the user system need send the custom reason to Exemption
	AccruableCOFINSExemptReasonTaxation string `json:"accruableCOFINSExemptReasonTaxation,omitempty"`

	// CSLL no withholding Custom Reason
	AccruableCSLLExemptReasonTaxation string `json:"accruableCSLLExemptReasonTaxation,omitempty"`

	// Support Buyer Tax Liability identifier for Federal Withholding Taxes. Each buyer may be subject/liable to withhold the following taxes independent to one another. The seller must be able to inform which Tax impacts the transaction based on a direct equivalency in the service item accrual. i.e. (The service item must be taxed by a given tax and the buyer must liable for the same tax withholding in order for the transaction to be taxable). To differentiate from the accrued taxes under the same acronyms the withholding taxes are followed by WH (this is a convention created for the sake of understanding and communicating the requirements. If false spite of all other settings.
	WithholdingPIS bool `json:"withholdingPIS,omitempty"`

	// Support Buyer Tax Liability identifier for Federal Withholding Taxes. Each buyer may be subject/liable to withhold the following taxes independent to one another. The seller must be able to inform which Tax impacts the transaction based on a direct equivalency in the service item accrual. i.e. (The service item must be taxed by a given tax and the buyer must liable for the same tax withholding in order for the transaction to be taxable). To differentiate from the accrued taxes under the same acronyms the withholding taxes are followed by WH (this is a convention created for the sake of understanding and communicating the requirements. If false spite of all other settings.
	WithholdingCOFINS bool `json:"withholdingCOFINS,omitempty"`

	// Support Buyer Tax Liability identifier for Federal Withholding Taxes. Each buyer may be subject/liable to withhold the following taxes independent to one another. The seller must be able to inform which Tax impacts the transaction based on a direct equivalency in the service item accrual. i.e. (The service item must be taxed by a given tax and the buyer must liable for the same tax withholding in order for the transaction to be taxable). To differentiate from the accrued taxes under the same acronyms the withholding taxes are followed by WH (this is a convention created for the sake of understanding and communicating the requirements. If false spite of all other settings.
	WithholdingCSLL bool `json:"withholdingCSLL,omitempty"`

	// Support Buyer Tax Liability identifier for Federal Withholding Taxes. Each buyer may be subject/liable to withhold the following taxes independent to one another. The seller must be able to inform which Tax impacts the transaction based on a direct equivalency in the service item accrual. i.e. (The service item must be taxed by a given tax and the buyer must liable for the same tax withholding in order for the transaction to be taxable). To differentiate from the accrued taxes under the same acronyms the withholding taxes are followed by WH (this is a convention created for the sake of understanding and communicating the requirements. If false spite of all other settings.
	WithholdingIRRF bool `json:"withholdingIRRF,omitempty"`

	// COFINS no withholding Custom Reason
	WithholdCOFINSExemptReasonTaxation string `json:"withholdCOFINSExemptReasonTaxation,omitempty"`

	// CSLL no withholding Custom Reason
	WithholdCSLLExemptReasonTaxation string `json:"withholdCSLLExemptReasonTaxation,omitempty"`

	// PIS no withholding Custom Reason
	WithholdPISExemptReasonTaxation string `json:"withholdPISExemptReasonTaxation,omitempty"`
}
