/**
 * AvaTax Brazil
 * The Avatax-Brazil API exposes the most commonly services available for interacting with the AvaTax-Brazil services, allowing calculation of taxes, issuing electronic invoice documents and modifying existing transactions when allowed by tax authorities.  This API is exclusively for use by business with a physical presence in Brazil.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import io.swagger.client.model.EntityType;
import io.swagger.client.model.FederalTaxRegime;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class SalesEntity {
  
  @SerializedName("name")
  private String name = null;
  @SerializedName("type")
  private EntityType type = null;
  @SerializedName("email")
  private String email = null;
  @SerializedName("cnpjcpf")
  private String cnpjcpf = null;
  @SerializedName("cityTaxId")
  private String cityTaxId = null;
  @SerializedName("stateTaxId")
  private String stateTaxId = null;
  @SerializedName("suframa")
  private String suframa = null;
  @SerializedName("phone")
  private String phone = null;
  @SerializedName("taxRegime")
  private FederalTaxRegime taxRegime = null;
  public enum SpecialTaxRegimeEnum {
     MEM,  EST,  SPR,  COP,  MEI,  MPP, 
  };
  @SerializedName("specialTaxRegime")
  private SpecialTaxRegimeEnum specialTaxRegime = null;
  @SerializedName("subjectToSRF1234")
  private Boolean subjectToSRF1234 = null;
  @SerializedName("requiredWithholdingISS")
  private Boolean requiredWithholdingISS = null;
  @SerializedName("art")
  private String art = null;
  @SerializedName("adminProcess")
  private String adminProcess = null;
  @SerializedName("buildCode")
  private String buildCode = null;

  /**
   * SERVICE BUYER NAME OFFICIAL
   **/
  @ApiModelProperty(value = "SERVICE BUYER NAME OFFICIAL")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public EntityType getType() {
    return type;
  }
  public void setType(EntityType type) {
    this.type = type;
  }

  /**
   * Entity Email
   **/
  @ApiModelProperty(value = "Entity Email")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * CNPJ/CPF of Sales Buyer, if CPF pattern is '[0-9]{11}' if CNPJ pattern is '[0-9]{14}'
   **/
  @ApiModelProperty(value = "CNPJ/CPF of Sales Buyer, if CPF pattern is '[0-9]{11}' if CNPJ pattern is '[0-9]{14}'")
  public String getCnpjcpf() {
    return cnpjcpf;
  }
  public void setCnpjcpf(String cnpjcpf) {
    this.cnpjcpf = cnpjcpf;
  }

  /**
   * City Tax ID
   **/
  @ApiModelProperty(value = "City Tax ID")
  public String getCityTaxId() {
    return cityTaxId;
  }
  public void setCityTaxId(String cityTaxId) {
    this.cityTaxId = cityTaxId;
  }

  /**
   * State Tax ID
   **/
  @ApiModelProperty(value = "State Tax ID")
  public String getStateTaxId() {
    return stateTaxId;
  }
  public void setStateTaxId(String stateTaxId) {
    this.stateTaxId = stateTaxId;
  }

  /**
   * Suframa ID
   **/
  @ApiModelProperty(value = "Suframa ID")
  public String getSuframa() {
    return suframa;
  }
  public void setSuframa(String suframa) {
    this.suframa = suframa;
  }

  /**
   * Entity Phone
   **/
  @ApiModelProperty(value = "Entity Phone")
  public String getPhone() {
    return phone;
  }
  public void setPhone(String phone) {
    this.phone = phone;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public FederalTaxRegime getTaxRegime() {
    return taxRegime;
  }
  public void setTaxRegime(FederalTaxRegime taxRegime) {
    this.taxRegime = taxRegime;
  }

  /**
   * Entity Special Tax Regime  - 'MEM' # Microempresa municipal - 'EST' # Estimativa - 'SPR' # Sociedade de profissionais - 'COP' # Cooperativa - 'MEI' # Microempresário Individual (MEI) - 'MPP' # Microempresário e Empresa de Pequeno Porte (ME EPP) 
   **/
  @ApiModelProperty(value = "Entity Special Tax Regime  - 'MEM' # Microempresa municipal - 'EST' # Estimativa - 'SPR' # Sociedade de profissionais - 'COP' # Cooperativa - 'MEI' # Microempresário Individual (MEI) - 'MPP' # Microempresário e Empresa de Pequeno Porte (ME EPP) ")
  public SpecialTaxRegimeEnum getSpecialTaxRegime() {
    return specialTaxRegime;
  }
  public void setSpecialTaxRegime(SpecialTaxRegimeEnum specialTaxRegime) {
    this.specialTaxRegime = specialTaxRegime;
  }

  /**
   * Companies subject to rule follow same rule of Government
   **/
  @ApiModelProperty(value = "Companies subject to rule follow same rule of Government")
  public Boolean getSubjectToSRF1234() {
    return subjectToSRF1234;
  }
  public void setSubjectToSRF1234(Boolean subjectToSRF1234) {
    this.subjectToSRF1234 = subjectToSRF1234;
  }

  /**
   * If Withholding ISS is required, independently the rules applied.
   **/
  @ApiModelProperty(value = "If Withholding ISS is required, independently the rules applied.")
  public Boolean getRequiredWithholdingISS() {
    return requiredWithholdingISS;
  }
  public void setRequiredWithholdingISS(Boolean requiredWithholdingISS) {
    this.requiredWithholdingISS = requiredWithholdingISS;
  }

  /**
   * technical note. Anota\\u00e7\\u00e3o de Responsabilidade T\\u00e9cnica-ART, estabelece que todos os contratos referentes à  execu\\u00e7\\u00e3o de servi\\u00e7os ou obras de Engenharia, Agronomia, Geologia, Geografia ou Meteorologia dever\\u00e3o ser objeto de anota\\u00e7\\u00e3o no Conselho Regional de Engenharia e Agronomia
   **/
  @ApiModelProperty(value = "technical note. Anota\\u00e7\\u00e3o de Responsabilidade T\\u00e9cnica-ART, estabelece que todos os contratos referentes à  execu\\u00e7\\u00e3o de servi\\u00e7os ou obras de Engenharia, Agronomia, Geologia, Geografia ou Meteorologia dever\\u00e3o ser objeto de anota\\u00e7\\u00e3o no Conselho Regional de Engenharia e Agronomia")
  public String getArt() {
    return art;
  }
  public void setArt(String art) {
    this.art = art;
  }

  /**
   * PROCESS NUMBER TO ISS SUSPENDED FOR ADMINISTRATIVE PROCESS
   **/
  @ApiModelProperty(value = "PROCESS NUMBER TO ISS SUSPENDED FOR ADMINISTRATIVE PROCESS")
  public String getAdminProcess() {
    return adminProcess;
  }
  public void setAdminProcess(String adminProcess) {
    this.adminProcess = adminProcess;
  }

  /**
   * Business code. Código da obra OBRA
   **/
  @ApiModelProperty(value = "Business code. Código da obra OBRA")
  public String getBuildCode() {
    return buildCode;
  }
  public void setBuildCode(String buildCode) {
    this.buildCode = buildCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SalesEntity salesEntity = (SalesEntity) o;
    return (this.name == null ? salesEntity.name == null : this.name.equals(salesEntity.name)) &&
        (this.type == null ? salesEntity.type == null : this.type.equals(salesEntity.type)) &&
        (this.email == null ? salesEntity.email == null : this.email.equals(salesEntity.email)) &&
        (this.cnpjcpf == null ? salesEntity.cnpjcpf == null : this.cnpjcpf.equals(salesEntity.cnpjcpf)) &&
        (this.cityTaxId == null ? salesEntity.cityTaxId == null : this.cityTaxId.equals(salesEntity.cityTaxId)) &&
        (this.stateTaxId == null ? salesEntity.stateTaxId == null : this.stateTaxId.equals(salesEntity.stateTaxId)) &&
        (this.suframa == null ? salesEntity.suframa == null : this.suframa.equals(salesEntity.suframa)) &&
        (this.phone == null ? salesEntity.phone == null : this.phone.equals(salesEntity.phone)) &&
        (this.taxRegime == null ? salesEntity.taxRegime == null : this.taxRegime.equals(salesEntity.taxRegime)) &&
        (this.specialTaxRegime == null ? salesEntity.specialTaxRegime == null : this.specialTaxRegime.equals(salesEntity.specialTaxRegime)) &&
        (this.subjectToSRF1234 == null ? salesEntity.subjectToSRF1234 == null : this.subjectToSRF1234.equals(salesEntity.subjectToSRF1234)) &&
        (this.requiredWithholdingISS == null ? salesEntity.requiredWithholdingISS == null : this.requiredWithholdingISS.equals(salesEntity.requiredWithholdingISS)) &&
        (this.art == null ? salesEntity.art == null : this.art.equals(salesEntity.art)) &&
        (this.adminProcess == null ? salesEntity.adminProcess == null : this.adminProcess.equals(salesEntity.adminProcess)) &&
        (this.buildCode == null ? salesEntity.buildCode == null : this.buildCode.equals(salesEntity.buildCode));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.type == null ? 0: this.type.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.cnpjcpf == null ? 0: this.cnpjcpf.hashCode());
    result = 31 * result + (this.cityTaxId == null ? 0: this.cityTaxId.hashCode());
    result = 31 * result + (this.stateTaxId == null ? 0: this.stateTaxId.hashCode());
    result = 31 * result + (this.suframa == null ? 0: this.suframa.hashCode());
    result = 31 * result + (this.phone == null ? 0: this.phone.hashCode());
    result = 31 * result + (this.taxRegime == null ? 0: this.taxRegime.hashCode());
    result = 31 * result + (this.specialTaxRegime == null ? 0: this.specialTaxRegime.hashCode());
    result = 31 * result + (this.subjectToSRF1234 == null ? 0: this.subjectToSRF1234.hashCode());
    result = 31 * result + (this.requiredWithholdingISS == null ? 0: this.requiredWithholdingISS.hashCode());
    result = 31 * result + (this.art == null ? 0: this.art.hashCode());
    result = 31 * result + (this.adminProcess == null ? 0: this.adminProcess.hashCode());
    result = 31 * result + (this.buildCode == null ? 0: this.buildCode.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class SalesEntity {\n");
    
    sb.append("  name: ").append(name).append("\n");
    sb.append("  type: ").append(type).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  cnpjcpf: ").append(cnpjcpf).append("\n");
    sb.append("  cityTaxId: ").append(cityTaxId).append("\n");
    sb.append("  stateTaxId: ").append(stateTaxId).append("\n");
    sb.append("  suframa: ").append(suframa).append("\n");
    sb.append("  phone: ").append(phone).append("\n");
    sb.append("  taxRegime: ").append(taxRegime).append("\n");
    sb.append("  specialTaxRegime: ").append(specialTaxRegime).append("\n");
    sb.append("  subjectToSRF1234: ").append(subjectToSRF1234).append("\n");
    sb.append("  requiredWithholdingISS: ").append(requiredWithholdingISS).append("\n");
    sb.append("  art: ").append(art).append("\n");
    sb.append("  adminProcess: ").append(adminProcess).append("\n");
    sb.append("  buildCode: ").append(buildCode).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
