=begin
#BR16 - API

#This documentation is about service accessories that will compose the product BR16, this services are essencial to maintenance and configuration of accounts

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module SwaggerClient
  class StateEnum
    
    AC = "AC".freeze
    AL = "AL".freeze
    AP = "AP".freeze
    AM = "AM".freeze
    BA = "BA".freeze
    CE = "CE".freeze
    DF = "DF".freeze
    ES = "ES".freeze
    GO = "GO".freeze
    MA = "MA".freeze
    MT = "MT".freeze
    MS = "MS".freeze
    MG = "MG".freeze
    PA = "PA".freeze
    PB = "PB".freeze
    PR = "PR".freeze
    PE = "PE".freeze
    PI = "PI".freeze
    RJ = "RJ".freeze
    RN = "RN".freeze
    RS = "RS".freeze
    RO = "RO".freeze
    RR = "RR".freeze
    SC = "SC".freeze
    SP = "SP".freeze
    SE = "SE".freeze
    TO = "TO".freeze
  end

end
