//
// InvoiceNFCeDANFEAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



open class InvoiceNFCeDANFEAPI: APIBase {

    public class func mapValuesToQueryItems(values: [String:Any?]) -> [URLQueryItem] {
        return values
            .filter { $0.1 != nil }
            .map { (item: (_key: String, _value: Any?)) -> URLQueryItem in
                URLQueryItem(name: item._key, value:"\(item._value!)")
            }
    }

    /**
     NFCe Danfe Print
     
     - parameter key: (path) Invoice Key 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func invoicesNfceKeyGet(key: String, completion: @escaping ((_ data: URL?,_ error: Error?) -> Void)) {
        invoicesNfceKeyGetWithRequestBuilder(key: key).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     NFCe Danfe Print
     - GET /invoices/nfce/{key}
     - Retrieve the Danfe in NFCe format. 
     - examples: [{output=none}]
     
     - parameter key: (path) Invoice Key 

     - returns: RequestBuilder<URL> 
     */
    open class func invoicesNfceKeyGetWithRequestBuilder(key: String) -> RequestBuilder<URL> {
        var path = "/invoices/nfce/{key}"
        path = path.replacingOccurrences(of: "{key}", with: "\(key)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:Any?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)

        let convertedParameters = APIHelper.convertBoolToString(parameters)

        let requestBuilder: RequestBuilder<URL>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
