=begin
#BR16 - API

#This documentation is about service accessories that will compose the product BR16, this services are essencial to maintenance and configuration of accounts

OpenAPI spec version: 1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::TaxByTypeSummaryForGoods
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'TaxByTypeSummaryForGoods' do
  before do
    # run before each test
    @instance = SwaggerClient::TaxByTypeSummaryForGoods.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TaxByTypeSummaryForGoods' do
    it 'should create an instact of TaxByTypeSummaryForGoods' do
      expect(@instance).to be_instance_of(SwaggerClient::TaxByTypeSummaryForGoods)
    end
  end
  describe 'test attribute "calcbase"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "tax"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "jurisdictions"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

